@Test
public void should_display_the_error_cause_and_the_cause_first_stack_trace_elements() {
    // GIVEN
    SoftAssertions softly = new SoftAssertions();
    softly.fail("failure", throwRuntimeException());
    // WHEN
    AssertionError error = catchThrowableOfType(() -> softly.assertAll(), AssertionError.class);
    // THEN
    assertThat(error).hasMessageStartingWith(format("%nMultiple Failures (1 failure)%n" + "-- failure 1 --" + "failure%n" + "at SoftAssertionsErrorDescriptionTest.should_display_the_error_cause_and_the_cause_first_stack_trace_elements(SoftAssertionsErrorDescriptionTest.java:28)"));
}
