@Test
public void testSyncAllUsersThrowingHandler2() throws Exception {
    syncMBean.syncAllExternalUsers();
    Map<String, String> expected = getExpectedUserResult("ERR", true);
    String[] result = createThrowingSyncMBean(true).syncAllUsers(false);
    assertResultMessages(result, expected);
}
