@Test
public void should_fail_if_completable_future_does_not_succeed_within_given_timeout() {
    // GIVEN
    int sleepDuration = 100000;
    CompletableFuture<String> future = completedFutureAfter("ook!", sleepDuration);
    // WHEN
    AssertionError assertionError = expectAssertionError(() -> assertThat(future).succeedsWithin(10, MILLISECONDS));
    // THEN
    then(assertionError).hasMessageStartingWith(format("%nExpecting%n" + "  <CompletableFuture[Incomplete]>%n" + "to be completed within 10L Millis.%n"));
}
