@Test
public void testContextVars() throws Exception {
    ELEvaluator.Context support = new ELEvaluator.Context();
    assertNull(support.getVariable("a"));
    support.setVariable("a", "A");
    assertEquals("A", support.getVariable("a"));
    Map<String, Object> vars = new HashMap<String, Object>();
    vars.put("a", "AA");
    vars.put("b", "BB");
    support.setVariables(vars);
    assertEquals("AA", support.getVariable("a"));
    assertEquals("BB", support.getVariable("b"));
    try {
        support.resolveVariable("c");
        fail();
    } catch (ELException ex) {
    // nop
    }
}
