@Test
public void testSyncExternalToExistingLocalUser() throws Exception {
    ExternalUser external = idp.listUsers().next();
    syncCtx.sync(external);
    User u = userManager.getAuthorizable(external.getId(), User.class);
    u.removeProperty(ExternalIdentityConstants.REP_EXTERNAL_ID);
    SyncResult result = syncCtx.sync(external);
    assertEquals(SyncResult.Status.FOREIGN, result.getStatus());
    SyncedIdentity si = result.getIdentity();
    assertNotNull(si);
    assertEquals(external.getExternalId(), si.getExternalIdRef());
}
