actual
given
read
expected
cause
INFO
catchThrowable
error
assertThat
any
assertHasDigest
 WHEN
inputStreams
 THEN
isInstanceOf
mock
should_throw_error_wrapping_caught_IOException
 GIVEN
willThrow
hasCause
MD5
