should_raise_an_error_because_of_non_public_getter_when_getter_is_in_superclass
No public getter for property 'name' in org.assertj.core.util.Introspection_getProperty_Test$Example
assertThatExceptionOfType
name
isThrownBy
getPropertyGetter
withMessage
